# Generated by Django 4.2.5 on 2024-03-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="image",
            field=models.CharField(max_length=10000),
        ),
    ]
