# Generated by Django 4.2.5 on 2024-03-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total",
            field=models.CharField(default="1", max_length=200),
            preserve_default=False,
        ),
    ]
